// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PubSubMessage.proto

package org.whispersystems.textsecuregcm.storage;

public final class PubSubProtos {
    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_textsecure_PubSubMessage_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_textsecure_PubSubMessage_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\023PubSubMessage.proto\022\ntextsecure\"\247\001\n\rPu" +
                        "bSubMessage\022,\n\004type\030\001 \001(\0162\036.textsecure.P" +
                        "ubSubMessage.Type\022\017\n\007content\030\002 \001(\014\"W\n\004Ty" +
                        "pe\022\013\n\007UNKNOWN\020\000\022\014\n\010QUERY_DB\020\001\022\013\n\007DELIVER" +
                        "\020\002\022\r\n\tKEEPALIVE\020\003\022\t\n\005CLOSE\020\004\022\r\n\tCONNECTE" +
                        "D\020\005B8\n(org.whispersystems.textsecuregcm." +
                        "storageB\014PubSubProtos"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_textsecure_PubSubMessage_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_textsecure_PubSubMessage_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_textsecure_PubSubMessage_descriptor,
                                new java.lang.String[]{"Type", "Content",});
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
    }

    private PubSubProtos() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface PubSubMessageOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // optional .textsecure.PubSubMessage.Type type = 1;

        /**
         * <code>optional .textsecure.PubSubMessage.Type type = 1;</code>
         */
        boolean hasType();

        /**
         * <code>optional .textsecure.PubSubMessage.Type type = 1;</code>
         */
        org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Type getType();

        // optional bytes content = 2;

        /**
         * <code>optional bytes content = 2;</code>
         */
        boolean hasContent();

        /**
         * <code>optional bytes content = 2;</code>
         */
        com.google.protobuf.ByteString getContent();
    }

    /**
     * Protobuf type {@code textsecure.PubSubMessage}
     */
    public static final class PubSubMessage extends
            com.google.protobuf.GeneratedMessage
            implements PubSubMessageOrBuilder {
        // optional .textsecure.PubSubMessage.Type type = 1;
        public static final int TYPE_FIELD_NUMBER = 1;
        // optional bytes content = 2;
        public static final int CONTENT_FIELD_NUMBER = 2;
        private static final PubSubMessage defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<PubSubMessage> PARSER =
                new com.google.protobuf.AbstractParser<PubSubMessage>() {
                    public PubSubMessage parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new PubSubMessage(input, extensionRegistry);
                    }
                };

        static {
            defaultInstance = new PubSubMessage(true);
            defaultInstance.initFields();
        }

        private final com.google.protobuf.UnknownFieldSet unknownFields;
        private int bitField0_;
        private org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Type type_;
        private com.google.protobuf.ByteString content_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use PubSubMessage.newBuilder() to construct.
        private PubSubMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
            this.unknownFields = builder.getUnknownFields();
        }

        private PubSubMessage(boolean noInit) {
            this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }
        private PubSubMessage(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();
                            org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Type value = org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Type.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(1, rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                type_ = value;
                            }
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            content_ = input.readBytes();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static PubSubMessage getDefaultInstance() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.whispersystems.textsecuregcm.storage.PubSubProtos.internal_static_textsecure_PubSubMessage_descriptor;
        }

        public static org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public PubSubMessage getDefaultInstanceForType() {
            return defaultInstance;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.whispersystems.textsecuregcm.storage.PubSubProtos.internal_static_textsecure_PubSubMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.class, org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Builder.class);
        }

        @java.lang.Override
        public com.google.protobuf.Parser<PubSubMessage> getParserForType() {
            return PARSER;
        }

        /**
         * <code>optional .textsecure.PubSubMessage.Type type = 1;</code>
         */
        public boolean hasType() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional .textsecure.PubSubMessage.Type type = 1;</code>
         */
        public org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Type getType() {
            return type_;
        }

        /**
         * <code>optional bytes content = 2;</code>
         */
        public boolean hasContent() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional bytes content = 2;</code>
         */
        public com.google.protobuf.ByteString getContent() {
            return content_;
        }

        private void initFields() {
            type_ = org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Type.UNKNOWN;
            content_ = com.google.protobuf.ByteString.EMPTY;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, type_.getNumber());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, content_);
            }
            getUnknownFields().writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, type_.getNumber());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, content_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf enum {@code textsecure.PubSubMessage.Type}
         */
        public enum Type
                implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>UNKNOWN = 0;</code>
             */
            UNKNOWN(0, 0),
            /**
             * <code>QUERY_DB = 1;</code>
             */
            QUERY_DB(1, 1),
            /**
             * <code>DELIVER = 2;</code>
             */
            DELIVER(2, 2),
            /**
             * <code>KEEPALIVE = 3;</code>
             */
            KEEPALIVE(3, 3),
            /**
             * <code>CLOSE = 4;</code>
             */
            CLOSE(4, 4),
            /**
             * <code>CONNECTED = 5;</code>
             */
            CONNECTED(5, 5),
            ;

            /**
             * <code>UNKNOWN = 0;</code>
             */
            public static final int UNKNOWN_VALUE = 0;
            /**
             * <code>QUERY_DB = 1;</code>
             */
            public static final int QUERY_DB_VALUE = 1;
            /**
             * <code>DELIVER = 2;</code>
             */
            public static final int DELIVER_VALUE = 2;
            /**
             * <code>KEEPALIVE = 3;</code>
             */
            public static final int KEEPALIVE_VALUE = 3;
            /**
             * <code>CLOSE = 4;</code>
             */
            public static final int CLOSE_VALUE = 4;
            /**
             * <code>CONNECTED = 5;</code>
             */
            public static final int CONNECTED_VALUE = 5;
            private static final Type[] VALUES = values();
            private static com.google.protobuf.Internal.EnumLiteMap<Type>
                    internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                        public Type findValueByNumber(int number) {
                            return Type.valueOf(number);
                        }
                    };
            private final int index;
            private final int value;

            private Type(int index, int value) {
                this.index = index;
                this.value = value;
            }

            public static Type valueOf(int value) {
                switch (value) {
                    case 0:
                        return UNKNOWN;
                    case 1:
                        return QUERY_DB;
                    case 2:
                        return DELIVER;
                    case 3:
                        return KEEPALIVE;
                    case 4:
                        return CLOSE;
                    case 5:
                        return CONNECTED;
                    default:
                        return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalGetValueMap() {
                return internalValueMap;
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.getDescriptor().getEnumTypes().get(0);
            }

            public static Type valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            public final int getNumber() {
                return value;
            }

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(index);
            }

            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }

            // @@protoc_insertion_point(enum_scope:textsecure.PubSubMessage.Type)
        }

        /**
         * Protobuf type {@code textsecure.PubSubMessage}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessageOrBuilder {
            private int bitField0_;
            // optional .textsecure.PubSubMessage.Type type = 1;
            private org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Type type_ = org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Type.UNKNOWN;
            // optional bytes content = 2;
            private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;

            // Construct using org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return org.whispersystems.textsecuregcm.storage.PubSubProtos.internal_static_textsecure_PubSubMessage_descriptor;
            }

            private static Builder create() {
                return new Builder();
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return org.whispersystems.textsecuregcm.storage.PubSubProtos.internal_static_textsecure_PubSubMessage_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.class, org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                type_ = org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Type.UNKNOWN;
                bitField0_ = (bitField0_ & ~0x00000001);
                content_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return org.whispersystems.textsecuregcm.storage.PubSubProtos.internal_static_textsecure_PubSubMessage_descriptor;
            }

            public org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage getDefaultInstanceForType() {
                return org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.getDefaultInstance();
            }

            public org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage build() {
                org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage buildPartial() {
                org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage result = new org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.type_ = type_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.content_ = content_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage) {
                    return mergeFrom((org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage other) {
                if (other == org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.getDefaultInstance())
                    return this;
                if (other.hasType()) {
                    setType(other.getType());
                }
                if (other.hasContent()) {
                    setContent(other.getContent());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional .textsecure.PubSubMessage.Type type = 1;</code>
             */
            public boolean hasType() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional .textsecure.PubSubMessage.Type type = 1;</code>
             */
            public org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Type getType() {
                return type_;
            }

            /**
             * <code>optional .textsecure.PubSubMessage.Type type = 1;</code>
             */
            public Builder setType(org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Type value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                type_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional .textsecure.PubSubMessage.Type type = 1;</code>
             */
            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                type_ = org.whispersystems.textsecuregcm.storage.PubSubProtos.PubSubMessage.Type.UNKNOWN;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes content = 2;</code>
             */
            public boolean hasContent() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional bytes content = 2;</code>
             */
            public com.google.protobuf.ByteString getContent() {
                return content_;
            }

            /**
             * <code>optional bytes content = 2;</code>
             */
            public Builder setContent(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                content_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes content = 2;</code>
             */
            public Builder clearContent() {
                bitField0_ = (bitField0_ & ~0x00000002);
                content_ = getDefaultInstance().getContent();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:textsecure.PubSubMessage)
        }

        // @@protoc_insertion_point(class_scope:textsecure.PubSubMessage)
    }

    // @@protoc_insertion_point(outer_class_scope)
}
